### PR TITLE
feat: sphinx documentation added

### LINKED ISSUE #8: Create a docs website

### PR DESCRIPTION
**Pull request by MihirRajeshPanchal**
closes #8 
## To generate Documentation Html File run code

```
pip install sphinx
sphinx-build -M html docs/source/ docs/build/
```
Open the index.html file in docs/build/html/index.html

image

image

### CODE REVIEW

**Comment by MihirRajeshPanchal** [comment]
@Bashamega the pull request solves #8

**Review by Bashamega — COMMENTED** [review]
Add the sphinx library in the requirements.txt

**Comment by MihirRajeshPanchal** [comment]
> Add the sphinx library in the requirements.txt

added it to requirements.txt sorry missed it by mistake

**Comment by Bashamega** [comment]
> > Add the sphinx library in the requirements.txt
> 
> added it to requirements.txt sorry missed it by mistake

no problem

**Review by Bashamega — APPROVED** [review]
Great work

**Comment by cools9** [comment]
Actually did you eat the code

**Review by cools9 — APPROVED** [review]

**Pull request merged**
